name: Run Benchmarks

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run benchmarks on'
        required: false
        default: 'main'

jobs:
  run-benchmarks:
    runs-on: ucc-benchmarks-8-core-U22.04

    steps:
      # Checkout the repository and branch
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure the full history is fetched
          ref: ${{ github.event.inputs.branch || 'main' }} # Checkout the branch specified by input or default to main

      # Set Git user for commit
      - name: Configure Git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ucc-benchmark .

      # Run the benchmarks in the Docker container
      - name: Run benchmarks
        run: |
          docker run --rm \
            -v "/home/runner/work/ucc/ucc:/ucc" \
            ucc-benchmark bash -c "
              source /venv/bin/activate && \
              ./benchmarks/scripts/small_test.sh && \
              python ./benchmarks/scripts/plot_avg_benchmarks_over_time.py && \
              python ./benchmarks/scripts/plot_latest_benchmarks.py
            "

      # Commit and push results to a new branch
      - name: Commit and push results to new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Set Git user name and email
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
          # Create a new branch for the benchmark results
          BRANCH_NAME="auto-benchmark-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME
      
          # Add and commit changes
          git add benchmarks/*
          git commit -m "Update benchmark results" || echo "No changes to commit"
      
          # Push the new branch to origin
          git push origin $BRANCH_NAME


      # Create a pull request
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_pr
        run: |
          PR_TITLE="Update benchmark results"
          RESPONSE=$(curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "$(jq -n \
                --arg title "$PR_TITLE" \
                --arg head "$BRANCH_NAME" \
                --arg base "main" \
                '{title: $title, head: $head, base: $base}')")
          echo "$RESPONSE" > pr_response.json
          PR_NUMBER=$(jq -r '.number' <<< "$RESPONSE")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      # Approve and merge the pull request
      - name: Auto-Approve and Merge Pull Request
        if: env.PR_NUMBER != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(cat pr_response.json | jq -r '.number')

          # Approve the PR
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews \
            -d '{"event": "APPROVE"}'

          # Merge the PR
          curl -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge \
            -d '{"merge_method": "squash"}'
