name: Run Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Run Docker Container
        run: |
          docker build -t ucc-benchmark .
          docker run --rm -v $PWD/benchmarks/results:/ucc/benchmarks/results ucc-benchmark

      - name: Commit and Push Results
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update benchmark results"
          add: "benchmarks/results"
